repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: [--line-length=88]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1   # <--- sửa lại đây
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: node
        types: [python]
        require_serial: true
        args:
          - --strict
          - --verbose
        pass_filenames: true
