# Generated by Django 4.2 on 2025-06-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="price_per_item",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
